# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ultraflow < Formula
  desc "Local board to run many AI coding agents in parallel over your CLI subscriptions"
  homepage "https://github.com/azdaev/ultraflow"
  version "0.10.0"
  license "MIT"

  depends_on "git"

  on_macos do
    url "https://github.com/azdaev/ultraflow/releases/download/v0.10.0/ultraflow_darwin_all.tar.gz"
    sha256 "041aa959b6db460454077a132d7057dc9e59796f8bc3d2ce1a4491a7b1825f3a"

    define_method(:install) do
      bin.install "ultraflow"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.0/ultraflow_linux_amd64.tar.gz"
      sha256 "cece0757a2d76a404cd25af6c7a98b1cd06aa98fc1bec2ffd25261d2aea0e30f"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.0/ultraflow_linux_arm64.tar.gz"
      sha256 "9e5766d8d0c1a5bdd855f0ab1bbf286ed21d0da3df104a2b4fc5c547bacac3fa"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
  end

  def caveats
    <<~EOS
      Ultraflow runs your own agent CLIs in headless mode — install and log in to
      at least one first (e.g. `claude`). Then run `ultraflow` and open
      http://localhost:7787.
    EOS
  end
end
