# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ultraflow < Formula
  desc "Local board to run many AI coding agents in parallel over your CLI subscriptions"
  homepage "https://github.com/azdaev/ultraflow"
  version "0.10.22"
  license "MIT"

  depends_on "git"

  on_macos do
    url "https://github.com/azdaev/ultraflow/releases/download/v0.10.22/ultraflow_darwin_all.tar.gz"
    sha256 "a12ede121e15c0e32635939caccab33638f5ebdced04a21be2cd1554fc577976"

    define_method(:install) do
      bin.install "ultraflow"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.22/ultraflow_linux_amd64.tar.gz"
      sha256 "9be2e8180475ffa71f0caf4a98fd247e3e222fddfebf3fad3e898495c1986b3c"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.22/ultraflow_linux_arm64.tar.gz"
      sha256 "7f2166330c635dcc36cfbefaaa8b5515afe3890a135e65d9ccc853a3cd40dc59"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
  end

  def caveats
    <<~EOS
      Ultraflow runs your own agent CLIs in headless mode — install and log in to
      at least one first (e.g. `claude`). Then run `ultraflow` and open
      http://localhost:7787.
    EOS
  end
end
