# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ultraflow < Formula
  desc "Local board to run many AI coding agents in parallel over your CLI subscriptions"
  homepage "https://github.com/azdaev/ultraflow"
  version "0.10.24"
  license "MIT"

  depends_on "git"

  on_macos do
    url "https://github.com/azdaev/ultraflow/releases/download/v0.10.24/ultraflow_darwin_all.tar.gz"
    sha256 "1cd78418f41e0d871a3f835fc9dda01e0bdbb30ac7680717d9e9bd11cfa0b89f"

    define_method(:install) do
      bin.install "ultraflow"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.24/ultraflow_linux_amd64.tar.gz"
      sha256 "928deaa94c5ff59fa3c6aec54a4c95be94875f8f274d6f3372e9e41fa9f74959"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azdaev/ultraflow/releases/download/v0.10.24/ultraflow_linux_arm64.tar.gz"
      sha256 "ebe8c27c04551f71ed88c07c33d23b88011d5aeb38027352c1571dec7e32ded9"
      define_method(:install) do
        bin.install "ultraflow"
      end
    end
  end

  def caveats
    <<~EOS
      Ultraflow runs your own agent CLIs in headless mode — install and log in to
      at least one first (e.g. `claude`). Then run `ultraflow` and open
      http://localhost:7787.
    EOS
  end
end
